services:
  db:
    profiles:
      -  development
    image:  postgres
    container_name:  postgress-db
    volumes:
      -  db-data:/var/lib/postgresql/data
    ports:
      -  "5432:5432"
    environment:
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=example
  app:
    profiles:
      -  development
    image: student-api
    build:
      # the "context" refer the starting location of Dockerfile and the starting location should always be at same level of docker-compose
      context:  dockerfiles
      # the "dockerfile" refer to the relative docker file location with respect to "context"
      dockerfile: ./App.Dockerfile
    container_name: api-server
    ports:
      - "8000:80"

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/sqldata